import Head from 'next/head'
import Image from 'next/image'
import { Button } from '@material-tailwind/react'


export default function Home() {
	return (
		<div>
			<Head>
				<title>Rick and Morty</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main>
				<h1 className="text-red-500 text-2xl">Test</h1>
				<Button>Button</Button>
			</main>
		</div>
	)
}
