import Head from 'next/head'
import Image from 'next/image'
import { Button } from '@material-tailwind/react'
import Cards from '../components/Cards'
import Navbar from '../components/Navbar'
import { getAllCharacters } from './api/charactersApi'
import SideBar from '../components/SideBar'

export default function Home({ characters }) {
	return (
		<div>
			<Head>
				<title>Rick and Morty</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className="m-10 w-full max-w-7xl h-full">
				<Navbar />
				<div className="flex w-full">
					<SideBar />
					<Cards characters={characters} />
				</div>
			</main>
		</div>
	)
}

export async function getStaticProps() {
	const characters = await getAllCharacters()

	return {
		props: {
			characters,
		},
	}
}