import Head from 'next/head'
import Image from 'next/image'
import { Button } from '@material-tailwind/react'
import Cards from '../components/Cards'
import Navbar from '../components/Navbar'
import { getAllCharacters } from './api/charactersApi'
import SideBar from '../components/SideBar'

export default function Home({ characters }) {
	return (
		<div>
			<Head>
				<title>Rick and Morty</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<header>
				<Navbar />
			</header>
			<main className="flex w-full max-w-6xl mx-auto h-full">
				<div className="w-full">
					<div className="flex w-full mt-20 justify-between">
						<SideBar characters={characters} />
						<Cards characters={characters} />
					</div>
				</div>
			</main>
		</div>
	)
}

export async function getStaticProps() {
	const characters = await getAllCharacters()

	return {
		props: {
			characters,
		},
	}
}